version: "3"
services: 
  db:
    image: "postgres:latest"
    container_name: db
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: db
    volumes:
    - ./my_data_directory:/var/lib/postgresql/data
    networks:
    - app_network

  server:
    image: server
    container_name: server
    build: ./server
    ports:
    - "8080:8080"
    networks:
    - app_network
    depends_on:
      - db
    
  frontend:
    image: client
    container_name: client
    build: ./client
    ports:
    - "3000:3000"
    networks:
    - app_network
    depends_on:
      - server

networks:
  app_network:
    driver: bridge
